manifesto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, primeiro_acesso, logout_view
from motorista.views import painel_view, verificar_cpf


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='login'),
    path('', include('mdfe.urls')),  # <--- isso é o importante!
    path('painel/', painel_view, name='painel'),  # sua view após login
    path('verificar-cpf/', verificar_cpf, name='verificar_cpf'),
    path('primeiro-acesso/', primeiro_acesso, name='primeiro_acesso'),
    path('logout/', logout_view, name='logout'),
]

mdfe/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mdfe/manifesto/<int:manifesto_id>/em_transporte/', views.iniciar_manifesto, name='iniciar_manifesto'),
    path('mdfe/manifesto/<int:manifesto_id>/ver', views.ver_manifesto, name='ver_manifesto'),



]

manifesto/forms.py
from django import forms

class PrimeiroAcessoForm(forms.Form):
    cpf = forms.CharField(max_length=11, widget=forms.HiddenInput())
    senha = forms.CharField(widget=forms.PasswordInput())
    confirmar_senha = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        senha = cleaned_data.get("senha")
        confirmar = cleaned_data.get("confirmar_senha")

        if senha != confirmar:
            self.add_error('confirmar_senha', "As senhas não coincidem.")

class LoginForm(forms.Form):
    cpf = forms.CharField(max_length=11)
    senha = forms.CharField(widget=forms.PasswordInput())

manifesto/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from motorista.utils import registrar_motoristas
from .forms import LoginForm, PrimeiroAcessoForm
from motorista.models import Motorista
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse

def login_view(request):
    registrar_motoristas() # Registra motoristas na base de dados
    if request.user.is_authenticated:
        return redirect('painel')  # Usuário já logado, redireciona para o painel

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cpf = form.cleaned_data['cpf']
            senha = form.cleaned_data['senha']
            user = authenticate(username=cpf, password=senha)
            if user:
                auth_login(request, user)  # Isso mantém o usuário logado
                # Redireciona para a página que o usuário estava tentando acessar
                return redirect(request.GET.get('next', 'painel'))
            else:
                form.add_error(None, "CPF ou senha incorretos.")
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})
    


def primeiro_acesso(request):
    if request.method == "POST":
        cpf = request.POST.get("cpf")
        senha = request.POST.get("senha")

        motorista = Motorista.objects.filter(cpf=cpf, user__isnull=True).first()
        if motorista:
            # Cria usuário com o CPF como username
            user = User.objects.create_user(username=cpf, password=senha)
            motorista.user = user
            motorista.save()
            return JsonResponse({"status": "ok"})
        else:
            return JsonResponse({"status": "erro", "mensagem": "Motorista não encontrado ou já possui conta"})
    return JsonResponse({"status": "erro", "mensagem": "Método inválido"})

# rota de logout
def logout_view(request):
    auth_logout(request)
    return redirect('login')

manifesto/templates/base.html
   <!-- Incluindo o header de um arquivo separado -->
   {% include 'include/header.html' %}

    <!-- Conteúdo da página -->

   <!-- Conteúdo principal -->
   <main>
   {% block content %}
   {% endblock %}
   </main>


   <!-- Incluindo o footer de um arquivo separado -->
   {% include 'include/footer.html' %}

   <!-- Scripts personalizados -->    
   {% block script %}{% endblock %} <!-- Corrigido aqui -->
   
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
 </body>

manifesto/templates/login.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
     <!-- Estilos da página -->

     <!-- Título da página -->
   <title>Login</title>
   
 </head>
 <body>
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
     
      <div class="col-md-8 col-lg-6 col-xl-4  ">

        <div class="login-app">
          <div class="container">
            <div class="heading">Seja Bem Vindo</div>
            <p class="text-center">Digite seu CPF para verificar seu cadastro</p>

            <form id="form-login" class="form" method="post">
              {% csrf_token %}
              <input required class="input" type="text" name="cpf" id="cpf" placeholder="CPF">

              <div id="senha-login" style="display: none;">
                <input required class="input" type="password" name="senha" id="senha" placeholder="Senha">
                <span class="forgot-password"><a href="#">Esqueceu sua senha?</a></span>
              </div>

              <div id="primeiro-acesso" style="display: none;">
                <input required class="input" type="password" name="nova_senha" id="nova_senha" placeholder="Nova senha">
                <input required class="input" type="password" name="confirmar_senha" id="confirmar_senha" placeholder="Confirmar senha">
              </div>

              <button class="login-button" type="button" id="btn-verificar">Verificar</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>



<script src="{% static 'js/verificacao.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</body>

manifesto/templates/primeiro_acesso.html
{% extends "base.html" %}
{% load static %}


{% block style %} 
<link rel="stylesheet" href="{% static '/css/login.css' %}">
{% endblock %}

{% block title %}Manifesto login{% endblock %}


{% block content %}
<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            <form method="post">
                {% csrf_token %}
            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
              <p class="lead fw-normal mb-0 me-3">Bem Vindo ao Manifesto</p>              
            </div>
  
            
  
            <!-- Email input -->
            <label class="form-label" for="form3Example3">CPF</label>
          <div data-mdb-input-init class="form-outline mb-4">
            <input type="text" id="id_cpf" class="form-control form-control-lg"
              placeholder="CPF Motorista" />
            
          </div>

          <!-- Password input -->
          <label class="form-label" for="form3Example4">Cadastra senha</label>

          <div data-mdb-input-init class="form-outline mb-3">
            <input type="password" id="id_senha" class="form-control form-control-lg"
              placeholder="Cadastra Senha" />
              {{ form.senha }}
          </div>
          <div data-mdb-input-init class="form-outline mb-3">
            <input type="password" id="id_senha" class="form-control form-control-lg"
              placeholder="Cadastra Senha" />
              {{ form.confirmar_senha }}
          </div>
  
            <div class="d-flex justify-content-between align-items-center">
              <!-- Checkbox -->
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                <label class="form-check-label" for="form2Example3">
                  Lembrar
                </label>
              </div>
              <a href="{% url 'login' %}" class="text-body">Ja tenho Senha</a>
            </div>
  
            <div class="text-center text-lg-start mt-4 pt-2">
              <button  type="submit" class="btn btn-primary"  data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">Cadastrar</button>
              
            </div>
  
          </form>
        </div>
      </div>
    </div>
   
  </section>
{% endblock %}

{% block script %}
<script src="{% static 'js/verificacao.js' %}" defer></script>
{% endblock %}